FROM node:14.19.3

LABEL maintainer "Daniel Roestorf <daniel.roestorf@maisonette.com>"

WORKDIR /app

COPY . .

ARG CMS_HOST
ARG DD_APPLICATION_ID
ARG DD_CLIENT_TOKEN
ARG GA_TRACKING_ID
ARG JWT_SECRET
ARG KLAVIYO_COMPANY_ID
ARG NEXT_PUBLIC_AMPLITUDE_KEY
ARG NEXT_PUBLIC_ASSET_HOST
ARG NEXT_PUBLIC_BRAINTREE_TOKEN
ARG NEXT_PUBLIC_CLIENT_HOST
ARG NEXT_PUBLIC_COOKIE_MAX_AGE
ARG NEXT_PUBLIC_GMAPS_KEY
ARG NEXT_PUBLIC_JIFITI_HOST
ARG NEXT_PUBLIC_PAYPAL_ENV
ARG NEXT_PUBLIC_PREVIEW_ASSET_HOST
ARG NEXT_PUBLIC_KUSTOMER_ACTIVE
ARG NEXT_PUBLIC_SHOW_EMAIL_MODAL
ARG KUSTOMER_API_KEY
ARG NODE_ENV
ARG PAYPAL_CLIENT_ID
ARG SALESFORCE_CLIENT_ID
ARG SALESFORCE_CLIENT_SECRET
ARG SALESFORCE_PASSWORD
ARG SALESFORCE_PRODUCTION_MODE
ARG SALESFORCE_SECURITY_TOKEN
ARG SALESFORCE_USERNAME
ARG SENTRY_AUTH_TOKEN
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_SENTRY_ENV
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ARG SLI_HOST
ARG SLI_LR_HOST
ARG SPEED_CURVE_ID
ARG SOLIDUS_HOST
ARG ZENDESK_API_KEY
ARG NEXT_PUBLIC_ALGOLIA_APP_ID
ARG NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY
ARG NEXT_PUBLIC_ALGOLIA_PRODUCTS_INDEX
ARG NEXT_PUBLIC_ALGOLIA_PRODUCTS_QUERY_SUGGESTIONS_INDEX
ARG NEXT_PUBLIC_ALGOLIA_CONTENTS_INDEX
ARG NEXT_PUBLIC_ALGOLIA_PRODUCTS_FREQUENTLY_BOUGHT
ARG NEXT_PUBLIC_ALGOLIA_PRODUCTS_RECOMMENDED
ARG FORTER_SITE_ID
ARG NEXT_PUBLIC_AFTERPAY_SDK
ARG NEXT_PUBLIC_LOAD_WUNDERKIND
ARG NEXT_PUBLIC_FASTLY_ON
ARG SOLIDUS_HOST_SEO
ARG SEO_MODE_ON

ENV CMS_HOST=${CMS_HOST} \
    DD_APPLICATION_ID=${DD_APPLICATION_ID} \
    DD_CLIENT_TOKEN=${DD_CLIENT_TOKEN} \
    GA_TRACKING_ID=${GA_TRACKING_ID} \
    JWT_SECRET=${JWT_SECRET} \
    KLAVIYO_COMPANY_ID=${KLAVIYO_COMPANY_ID} \
    NEXT_PUBLIC_AMPLITUDE_KEY=${NEXT_PUBLIC_AMPLITUDE_KEY} \
    NEXT_PUBLIC_ASSET_HOST=${NEXT_PUBLIC_ASSET_HOST} \
    NEXT_PUBLIC_BRAINTREE_TOKEN=${NEXT_PUBLIC_BRAINTREE_TOKEN} \
    NEXT_PUBLIC_CLIENT_HOST=${NEXT_PUBLIC_CLIENT_HOST} \
    NEXT_PUBLIC_COOKIE_MAX_AGE=${NEXT_PUBLIC_COOKIE_MAX_AGE} \
    NEXT_PUBLIC_GMAPS_KEY=${NEXT_PUBLIC_GMAPS_KEY} \
    NEXT_PUBLIC_JIFITI_HOST=${NEXT_PUBLIC_JIFITI_HOST} \
    NEXT_PUBLIC_PAYPAL_ENV=${NEXT_PUBLIC_PAYPAL_ENV} \
    NEXT_PUBLIC_PREVIEW_ASSET_HOST=${NEXT_PUBLIC_PREVIEW_ASSET_HOST} \
    NEXT_PUBLIC_KUSTOMER_ACTIVE=${NEXT_PUBLIC_KUSTOMER_ACTIVE} \
    NEXT_PUBLIC_SHOW_EMAIL_MODAL=${NEXT_PUBLIC_SHOW_EMAIL_MODAL} \
    KUSTOMER_API_KEY=${KUSTOMER_API_KEY} \
    NODE_ENV=${NODE_ENV} \
    PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID} \
    SALESFORCE_CLIENT_ID=${SALESFORCE_CLIENT_ID} \
    SALESFORCE_CLIENT_SECRET=${SALESFORCE_CLIENT_SECRET} \
    SALESFORCE_PASSWORD=${SALESFORCE_PASSWORD} \
    SALESFORCE_PRODUCTION_MODE=${SALESFORCE_PRODUCTION_MODE} \
    SALESFORCE_SECURITY_TOKEN=${SALESFORCE_SECURITY_TOKEN} \
    SALESFORCE_USERNAME=${SALESFORCE_USERNAME} \
    SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN} \
    NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} \
    NEXT_PUBLIC_SENTRY_ENV=${NEXT_PUBLIC_SENTRY_ENV} \
    SENTRY_ORG=${SENTRY_ORG} \
    SENTRY_PROJECT=${SENTRY_PROJECT} \
    SLI_HOST=${SLI_HOST} \
    SLI_LR_HOST=${SLI_LR_HOST} \
    SPEED_CURVE_ID=${SPEED_CURVE_ID} \
    SOLIDUS_HOST=${SOLIDUS_HOST} \
    ZENDESK_API_KEY=${ZENDESK_API_KEY} \
    NEXT_PUBLIC_ALGOLIA_APP_ID=${NEXT_PUBLIC_ALGOLIA_APP_ID} \
    NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=${NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY} \
    NEXT_PUBLIC_ALGOLIA_PRODUCTS_INDEX=${NEXT_PUBLIC_ALGOLIA_PRODUCTS_INDEX} \
    NEXT_PUBLIC_ALGOLIA_PRODUCTS_QUERY_SUGGESTIONS_INDEX=${NEXT_PUBLIC_ALGOLIA_PRODUCTS_QUERY_SUGGESTIONS_INDEX} \
    NEXT_PUBLIC_ALGOLIA_CONTENTS_INDEX=${NEXT_PUBLIC_ALGOLIA_CONTENTS_INDEX} \
    NEXT_PUBLIC_ALGOLIA_PRODUCTS_FREQUENTLY_BOUGHT=${NEXT_PUBLIC_ALGOLIA_PRODUCTS_FREQUENTLY_BOUGHT} \
    NEXT_PUBLIC_ALGOLIA_PRODUCTS_RECOMMENDED=${NEXT_PUBLIC_ALGOLIA_PRODUCTS_RECOMMENDED} \
    FORTER_SITE_ID=${FORTER_SITE_ID} \
    NEXT_PUBLIC_AFTERPAY_SDK=${NEXT_PUBLIC_AFTERPAY_SDK} \
    NEXT_PUBLIC_LOAD_WUNDERKIND=${NEXT_PUBLIC_LOAD_WUNDERKIND} \
    NEXT_PUBLIC_FASTLY_ON=${NEXT_PUBLIC_FASTLY_ON} \
    SOLIDUS_HOST_SEO=${SOLIDUS_HOST_SEO} \
    SEO_MODE_ON=${SEO_MODE_ON}

ARG NOCRAWL=false
RUN apt-get update
RUN apt-get install -y jq openssh-client
RUN if $(${NOCRAWL}) ; then printf "User-agent: Screaming Frog SEO Spider\nAllow: /\n\nUser-agent: Pinterest\nAllow: /\n\nUser-agent: *\nDisallow: /\n" > public/robots.txt ; fi

RUN npm config set unsafe-perm true

RUN npm install -g \
    react@$(cat package.json | jq -r .dependencies.react) \
    react-dom@$(cat package.json | jq -r '.dependencies["react-dom"]') \
    next@$(cat package.json | jq -r .dependencies.next)
RUN npm install
RUN npm run build

RUN ./patch-server.sh

EXPOSE 7777

CMD ["npm", "run", "start"]
